import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import { Navbar } from "@/components/Navbar";

const roboto = Roboto({ weight: ['400', '700'], preload: false })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className="antialiased">
      <body className={`${roboto.className}  overflow-x-hidden`}>
        <div className='w-screen h-full bg-background'>
          <div className='max-w-5xl m-auto '>
            <Navbar />
            <main className="bg-background pb-10 pt-8 w-6xl">{children}</main>
          </div>
        </div>
      </body>
        
    </html>
  )
}
